//! Human-readable 6502 source listing produced from codegen metadata.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt::Write;
use std::path::Path;

use super::{MemoryMap, codegen::listing_opcode};

pub fn generate(map: &MemoryMap, source_path: Option<&Path>) -> String {
    let mut out = String::new();
    writeln!(out, "; Generated by Ultimate Basic").unwrap();
    if let Some(path) = source_path {
        writeln!(out, "; Source: {}", path.display()).unwrap();
    }
    writeln!(
        out,
        "; Reassemblable KickAssembler source generated from codegen metadata.\n"
    )
    .unwrap();

    for var in &map.variables {
        writeln!(
            out,
            ".label {:<17} = ${:02X} ; {}",
            symbol(&var.name),
            var.zp_addr,
            var.type_str
        )
        .unwrap();
    }
    for array in &map.arrays {
        writeln!(
            out,
            ".label {:<17} = ${:04X} ; {} bytes",
            symbol(&array.name),
            array.base_addr,
            array.size
        )
        .unwrap();
    }
    if !map.variables.is_empty() || !map.arrays.is_empty() {
        out.push('\n');
    }
    writeln!(out, "* = ${:04X}\n", map.load_addr).unwrap();

    let mut named = BTreeMap::<u16, String>::new();
    named.insert(map.load_addr, "ub_start".into());
    for sub in &map.subroutines {
        named.insert(sub.addr, symbol(&sub.name));
    }
    for label in &map.labels {
        named.insert(label.addr, symbol(&label.name));
    }
    for item in &map.listing_symbols {
        named.insert(
            map.load_addr.wrapping_add(item.offset as u16),
            symbol(&item.name),
        );
    }
    for region in &map.data_regions {
        named.insert(
            map.load_addr.wrapping_add(region.start as u16),
            symbol(&region.name),
        );
    }

    let mut branch_targets = BTreeSet::new();
    let mut pos = 0usize;
    while pos < map.code_bytes.len() {
        if let Some(region) = data_region_at(map, pos) {
            pos = region.end;
            continue;
        }
        let op = map.code_bytes[pos];
        let Some((mnem, mode, size)) = listing_opcode(op) else {
            pos += 1;
            continue;
        };
        if pos + size > map.code_bytes.len() {
            break;
        }
        if mode == "rel" {
            let pc = map.load_addr.wrapping_add(pos as u16);
            let rel = map.code_bytes[pos + 1] as i8 as i16;
            branch_targets.insert(pc.wrapping_add(2).wrapping_add(rel as u16));
        } else if mode == "abs" && matches!(mnem, "JMP" | "JSR") {
            let target = u16::from_le_bytes([map.code_bytes[pos + 1], map.code_bytes[pos + 2]]);
            let end = map.load_addr.wrapping_add(map.code_bytes.len() as u16);
            if target >= map.load_addr && target < end {
                branch_targets.insert(target);
            }
        }
        pos += size;
    }
    for addr in branch_targets {
        named
            .entry(addr)
            .or_insert_with(|| format!("loc_{addr:04X}"));
    }

    let zp_names: HashMap<u8, String> = map
        .variables
        .iter()
        .map(|v| (v.zp_addr, symbol(&v.name)))
        .collect();
    let mut comments: BTreeMap<usize, Vec<&str>> = BTreeMap::new();
    for span in &map.listing_spans {
        comments.entry(span.start).or_default().push(&span.source);
    }

    pos = 0;
    while pos < map.code_bytes.len() {
        let addr = map.load_addr.wrapping_add(pos as u16);
        if let Some(label) = named.get(&addr) {
            writeln!(out, "{label}:").unwrap();
        }
        if let Some(items) = comments.get(&pos) {
            for item in items.iter().rev() {
                writeln!(out, "    ; UB: {item}").unwrap();
            }
        }

        if let Some(region) = data_region_at(map, pos) {
            write_data_region(&mut out, map, region);
            pos = region.end;
            continue;
        }

        let opcode = map.code_bytes[pos];
        let Some((mnem, mode, size)) = listing_opcode(opcode) else {
            writeln!(out, "    .byte ${opcode:02X}              ; ${addr:04X}").unwrap();
            pos += 1;
            continue;
        };
        if pos + size > map.code_bytes.len() {
            writeln!(
                out,
                "    .byte ${opcode:02X}              ; ${addr:04X} truncated"
            )
            .unwrap();
            pos += 1;
            continue;
        }
        let operand = format_operand(
            mode,
            addr,
            &map.code_bytes[pos + 1..pos + size],
            &named,
            &zp_names,
        );
        let bytes = map.code_bytes[pos..pos + size]
            .iter()
            .map(|b| format!("{b:02X}"))
            .collect::<Vec<_>>()
            .join(" ");
        writeln!(
            out,
            "    {:<4} {:<22} ; ${addr:04X}: {bytes}",
            mnem.to_ascii_lowercase(),
            operand
        )
        .unwrap();
        pos += size;
    }
    out
}

fn data_region_at(map: &MemoryMap, offset: usize) -> Option<&super::DataRegion> {
    map.data_regions
        .iter()
        .filter(|region| region.start <= offset && offset < region.end)
        .min_by_key(|region| region.start)
}

fn write_data_region(out: &mut String, map: &MemoryMap, region: &super::DataRegion) {
    let bytes = &map.code_bytes[region.start..region.end];
    let start_addr = map.load_addr.wrapping_add(region.start as u16);
    writeln!(out, "    ; data: {} ({} bytes)", region.name, bytes.len()).unwrap();
    if bytes.iter().all(|&byte| byte == 0) && bytes.len() > 16 {
        writeln!(
            out,
            "    .fill {}, $00               ; ${start_addr:04X}-${:04X}",
            bytes.len(),
            start_addr.wrapping_add(bytes.len() as u16).wrapping_sub(1)
        )
        .unwrap();
        return;
    }
    for (line, chunk) in bytes.chunks(16).enumerate() {
        let addr = start_addr.wrapping_add((line * 16) as u16);
        let values = chunk
            .iter()
            .map(|byte| format!("${byte:02X}"))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "    .byte {values:<79} ; ${addr:04X}").unwrap();
    }
}

fn format_operand(
    mode: &str,
    pc: u16,
    bytes: &[u8],
    named: &BTreeMap<u16, String>,
    zp: &HashMap<u8, String>,
) -> String {
    let b = bytes.first().copied().unwrap_or(0);
    let word = || u16::from_le_bytes([b, bytes.get(1).copied().unwrap_or(0)]);
    let abs = || {
        named
            .get(&word())
            .cloned()
            .unwrap_or_else(|| format!("${:04X}", word()))
    };
    let zpv = || zp.get(&b).cloned().unwrap_or_else(|| format!("${b:02X}"));
    match mode {
        "acc" => "a".into(),
        "imp" => String::new(),
        "imm" => format!("#${b:02X}"),
        "zp" => zpv(),
        "zpx" => format!("{},x", zpv()),
        "zpy" => format!("{},y", zpv()),
        "izx" => format!("({},x)", zpv()),
        "izy" => format!("({}),y", zpv()),
        "abs" => abs(),
        "abx" => format!("{},x", abs()),
        "aby" => format!("{},y", abs()),
        "ind" => format!("({})", abs()),
        "rel" => {
            let target = pc.wrapping_add(2).wrapping_add((b as i8 as i16) as u16);
            named
                .get(&target)
                .cloned()
                .unwrap_or_else(|| format!("${target:04X}"))
        }
        _ => String::new(),
    }
}

fn symbol(name: &str) -> String {
    let mut result: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if result.as_bytes().first().is_some_and(u8::is_ascii_digit) {
        result.insert(0, '_');
    }
    result
}

#[cfg(test)]
mod tests {
    use crate::compiler::{CompileOptions, compile};

    #[test]
    fn listing_contains_symbols_statements_and_instructions() {
        let result = compile(
            "var x = 1\nx = x + 1\nprint x\n",
            &CompileOptions { basic_stub: false, explicit: false },
        );
        assert!(result.asm.contains(".label x                 = $02"));
        assert!(result.asm.contains("; UB: var x"));
        assert!(result.asm.contains("lda  #$01"));
        assert!(result.asm.contains("sta  x"));
    }

    #[test]
    fn listing_names_helpers_and_keeps_data_as_bytes() {
        let result = compile(
            "graphics on\nplot 1, 2\nvar x = 0\ndata 1, 2, 3\nread x\n",
            &CompileOptions { basic_stub: false, explicit: false },
        );
        assert!(result.asm.contains("* = $0801"));
        assert!(result.asm.contains("ub_helper_plot:"));
        assert!(result.asm.contains("jsr  ub_helper_plot"));
        assert!(result.asm.contains("ub_data:"));
        assert!(result.asm.contains(".byte $01, $02, $03"));
    }
}
